package main // Code generated by gintool. DO NOT EDIT.

import (
	"github.com/gin-gonic/gin"
	"xyz/dbettkk/btc/biz/handler"
)

// register register routes based on the IDL 'api.${HTTP Method}' annotation.
func register(r *gin.Engine) {
	customizeRegister(r)

	r.GET("/ping", handler.Ping)
}
